language: cpp

os: linux
dist: xenial

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt562-xenial'
    packages:
      - libgl1-mesa-dev
      - qt56base
      - qt56declarative

install:
  - source /opt/qt56/bin/qt56-env.sh

script:
  - mkdir build
  - cd build
  - qmake ..
  - make -j4

notifications:
  irc:
    channels:
      - "irc.choopa.net#firebird-emu"
    on_success: change
    on_failure: always
    skip_join: true
